#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 2:00:00
#SBATCH -J busco_polished
#SBATCH --mail-type=ALL
#SBATCH --mail-user mariia.chubataia.8934@student.uu.se
#SBATCH --output=%x.%j.out

# Load modules

module load bioinfo-tools
module load BUSCO/5.7.1
source $AUGUSTUS_CONFIG_COPY

# Your commands
busco -i /home/mach8934/genome_analysis/data/03_polished_data/polished_assembly.fasta \
      -l $BUSCO_LINEAGE_SETS/embryophyta_odb10/ \
      -o /home/mach8934/genome_analysis/data/04_quality_assesment/out_BUSCO/busco_polished \
      -m genome \
      -c 4 \
      -f

